default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bbq_development


test:
  <<: *default
  database: bbq_test


production:
  <<: *default
  database: <%= Rails.application.credentials.production_db[:database] %>
  username: <%= Rails.application.credentials.production_db[:username] %>
  password: <%= Rails.application.credentials.production_db[:password] %>
